<?php

/**
 * @param $node
 *
 * Description: This hook is invoked from node_save() after the database query that will insert the node into the node table is scheduled for execution,
 * after the type-specific hook_insert() is invoked, and after field_attach_insert() is called.
 *
 */
function show_message_node_insert($node){
    if($node->getType() == "article"){
        drupal_set_message(t("Go ahead and check if you haven't made any mistakes."));
    }
}